### ISSUE TITLE
Install command doesn't work

### ISSUE THREAD

**Issue by nabilamiri** [thewh1teagle/Evpn#1]
Hello,

Attempting to use this but the install via pip3 doesn't work. No version can be found.

**Comment by thewh1teagle** [comment]
Hi, you right. 
for some reason the package isn't uploaded to pypi. 
I made new release `1.0.3` and uploaded it to pypi. 
can you try again?

**Comment by nabilamiri** [comment]
able to install, but receiving this error: 
FileNotFoundError: [Errno 2] No such file or directory: PosixPath('/usr/bin/expressvpn-browser-helper')

**Comment by thewh1teagle** [comment]
Please try to give more details next time. 
now:
1. what's your operation system? 
2. version?
3. Have you installed expressvpn? if so, which version of expressvpn?
4. Can you verify if the file `/usr/bin/expressvpn-browser-helper` exists?
